"""Centralised CLI exit codes (spec §7)."""

OK = 0
USAGE = 2
ACCESSORY_UNREACHABLE = 10
NOT_PAIRED = 11
PAIRING_FAILED = 12
CHARACTERISTIC_INVALID = 13
CONNECTION_LIMIT = 14
PAIRING_STORE_CORRUPT = 15
POLICY_BLOCKED = 16
